# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/idiyp/Downloads/EEE4120F-master/EEE4120F-master/Prac3/Prac3_2_Code/matrix_mat/matrix_mat.srcs/sources_1/ip/matrix_a/matrix_a.xci
# IP: The module: 'matrix_a' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/idiyp/Downloads/EEE4120F-master/EEE4120F-master/Prac3/Prac3_2_Code/matrix_mat/matrix_mat.gen/sources_1/ip/matrix_a/matrix_a_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matrix_a'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/idiyp/Downloads/EEE4120F-master/EEE4120F-master/Prac3/Prac3_2_Code/matrix_mat/matrix_mat.srcs/sources_1/ip/matrix_a/matrix_a.xci
# IP: The module: 'matrix_a' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/idiyp/Downloads/EEE4120F-master/EEE4120F-master/Prac3/Prac3_2_Code/matrix_mat/matrix_mat.gen/sources_1/ip/matrix_a/matrix_a_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matrix_a'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
